POST http://localhost:3000/user/reg
Content-Type: application/json

{
    "regNo": "12308021",
    "password": "someone123@2005",
    "skills": ["python", "java", "c++"]
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "regNo": "12308019",
    "password": "pooja@2005"
}

###

POST http://localhost:3000/user/suggestions
Content-Type: application/json

{
    "skills": ["c++"]
}

###

GET http://localhost:3000/user/logout

###

POST http://localhost:3000/user/friend-req
Content-Type: application/json

{
    "regNo": "12308021",
    "friendRegNo": "12308018"
}

###

GET http://localhost:3000/user/friend-req/12308018


###

PUT http://localhost:3000/user/accept-friend-req
Content-Type: application/json

{
    "regNo": "12308018",
    "friendRegNo": "12308021"
}