POST http://localhost:3000/user/reg
Content-Type: application/json

{
    "regNo": "12308021",
    "password": "someone123@2005",
    "skills": ["python", "java", "c++"]
}

###

POST http://localhost:3000/user/login
Content-Type: application/json

{
    "regNo": "12308019",
    "password": "pooja@2005"
}

###

POST http://localhost:3000/user/suggestions
Content-Type: application/json

{
    "skills": ["c++"]
}

###

GET http://localhost:3000/user/logout